<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Dotnet.PackageExplorer.RpcClient</AssemblyName>
        <RootNamespace>Dotnet.PackageExplorer.RpcClient</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
        <Compile Include="Protocol.fs" />
        <Compile Include="PackageMapping.fs" />
        <Compile Include="ProcessSession.fs" />
        <Compile Include="Client.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Application/Dotnet.PackageExplorer.Application.fsproj" />
        <PackageReference Include="FSharp.Core" />
        <PackageReference Include="MessagePack" />
    </ItemGroup>
</Project>
