<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Dotnet.PackageExplorer.Application</AssemblyName>
        <RootNamespace>Dotnet.PackageExplorer.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Domain.fs" />
        <Compile Include="Client.fs" />
        <Compile Include="Model.fs" />
        <Compile Include="Update.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>
</Project>
