<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Dotnet.PackageExplorer.Application</AssemblyName>
        <RootNamespace>Dotnet.PackageExplorer.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>
</Project>
